### ISSUE TITLE
앱 외 라벨링

### ISSUE THREAD

**Issue by gowoon-choi** [Nexters/Full-Stack-Android#4]
**DONE**
- [x] 스크린샷 후 공유하기로 서비스 접근
- [x] 라벨링 화면 ( 스크린샷 로드, 내 라벨 리스트 로드 )
- [x] 라벨링 ( 라벨 선택 및 해제 )

**WIP**
- [x] 라벨 검색 
- edittext 관련 기본 ui 설정 ( cursor drawable 등등 )
- edittext focus/enable 관리 ( 상태별 뷰 변화, 이벤트 및 터치 영역에 따른 상태 관리 등등 )
- 키보드 관련 기본 설정 ( imeOpt, adjustresize 등등 )
- 검색어 입력 ( xml - viewmodel livedata twoway databinding )
- 검색결과 

**TODO**
- [x] 라벨 생성
- [ ] 라벨링 완료 후 플로우

**PENDING**
#25
